name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUCKET_NAME : "typescript-express-artifact"
  AWS_REGION : "ap-south-1"

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read    

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::464615698121:role/GitHub-actions-Role
          aws-region: ${{ env.AWS_REGION }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract commit hash
        shell: bash
        run: echo "##[set-output name=commit_hash;]$(echo "$GITHUB_SHA")"
        id: extract_hash          
      - run: npm ci
      - run: npm run build
      - run: npm run lint

      - name: Copy artifact to the S3 bucket
        run: |
          aws s3 sync --delete ./dist s3://${{ env.BUCKET_NAME }}/${{ steps.extract_branch.outputs.branch }}/${{ steps.extract_hash.outputs.commit_hash }}